# Generated by Django 3.1.4 on 2020-12-14 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_ID', models.CharField(max_length=50)),
                ('contractor_Name', models.CharField(max_length=255)),
                ('contractor_pass', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=255)),
                ('specialties', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grade_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('Assignment_name', models.CharField(max_length=200)),
                ('Grade', models.CharField(max_length=200)),
                ('Out_Of_Grade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('details', models.TextField(max_length=200)),
                ('attachment', models.FileField(max_length=200, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=200)),
                ('Plan', models.CharField(max_length=200)),
                ('Enrollment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='status_vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='store_email_staff_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_ID', models.CharField(max_length=100)),
                ('Staff_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='store_email_stu_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(max_length=100)),
                ('Student_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='store_email_teach_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_ID', models.CharField(max_length=100)),
                ('Teacher_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student_courses_with_Teacher_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Login_informations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(max_length=50)),
                ('Student_Name', models.CharField(max_length=255)),
                ('Student_pass', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Submit_Assignment_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.CharField(max_length=1000)),
                ('course', models.CharField(max_length=1000)),
                ('Student_ID', models.CharField(max_length=1000)),
                ('Assignment_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Assignment_upload_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assignment_name', models.CharField(max_length=500)),
                ('course', models.CharField(max_length=500)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 12, 14, 23, 41, 36, 766829))),
                ('due_date', models.DateField(blank=True, default=datetime.datetime(2020, 12, 14, 23, 41, 36, 766829))),
                ('title', models.CharField(max_length=500)),
                ('Details', models.TextField(max_length=500)),
                ('attachment', models.CharField(max_length=1000)),
                ('resource', models.CharField(max_length=500)),
                ('posts', models.CharField(max_length=500)),
                ('Out_Of_Grade', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_login_informa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_ID', models.CharField(max_length=50)),
                ('Teacher_Name', models.CharField(max_length=255)),
                ('Teacher_pass', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_staff_ID', models.CharField(max_length=50)),
                ('user_staffuser_Name', models.CharField(max_length=255)),
                ('user_staff_pass', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Timeoff_user_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 12, 14, 23, 41, 36, 769826))),
                ('requested_days', models.CharField(max_length=150)),
                ('reason', models.TextField(max_length=150)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.status_vacation')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.CharField(max_length=500)),
                ('ID_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.admission')),
                ('ID_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_courses_with_teacher_name')),
                ('ID_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.school')),
            ],
        ),
        migrations.AddField(
            model_name='student_courses_with_teacher_name',
            name='Teacher_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.teacher_login_informa'),
        ),
        migrations.CreateModel(
            name='Student_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_login_informations')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_courses_with_teacher_name')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.school')),
                ('ID_faculties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.faculties')),
                ('ID_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.students')),
                ('ID_user_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.user_staff')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Comments_all',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('postID', models.CharField(max_length=255)),
                ('time_comment', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 14, 23, 41, 36, 768827))),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.assignment_comments_all')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.teacher_assignment_upload_file')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='ID_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_courses_with_teacher_name'),
        ),
        migrations.AddField(
            model_name='admission',
            name='ID_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.school'),
        ),
        migrations.AddField(
            model_name='admission',
            name='ID_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_login_informations'),
        ),
    ]
