# Generated by Django 3.1.4 on 2020-12-18 05:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0018_auto_20201218_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_comments_all',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 11, 30, 8, 785094)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 18, 11, 30, 8, 783095)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 18, 11, 30, 8, 783095)),
        ),
        migrations.AlterField(
            model_name='timeoff_user_all',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 18, 11, 30, 8, 786093)),
        ),
        migrations.CreateModel(
            name='store_email_staffs_by_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_email', models.CharField(max_length=30)),
                ('Staff_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.add_staffs_by_manager')),
            ],
        ),
    ]
