# Generated by Django 3.1.4 on 2020-12-18 09:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0022_auto_20201218_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_comments_all',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 18, 15, 14, 38, 973252)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 18, 15, 14, 38, 972253)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 18, 15, 14, 38, 972253)),
        ),
        migrations.AlterField(
            model_name='timeoff_user_all',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 18, 15, 14, 38, 974251)),
        ),
        migrations.CreateModel(
            name='Timeoff_staff_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 12, 18, 15, 14, 38, 975250))),
                ('requested_days', models.CharField(max_length=150)),
                ('reason', models.TextField(max_length=150)),
                ('Manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.manager_login_information')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.status_vacation')),
            ],
        ),
    ]
