# Generated by Django 3.1.4 on 2020-12-20 03:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0024_auto_20201218_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_comments_all',
            name='postID',
            field=models.CharField(max_length=25500),
        ),
        migrations.AlterField(
            model_name='assignment_comments_all',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 20, 9, 50, 25, 699051)),
        ),
        migrations.AlterField(
            model_name='assignment_comments_all',
            name='user',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='grade_student',
            name='course',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='Details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='attachment',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 20, 9, 50, 25, 697053)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 20, 9, 50, 25, 697053)),
        ),
        migrations.AlterField(
            model_name='timeoff_staff_teacher',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 20, 9, 50, 25, 700052)),
        ),
        migrations.CreateModel(
            name='Timeoff_staffs_teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 12, 20, 9, 50, 25, 701051))),
                ('requested_days', models.CharField(max_length=150)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=1500)),
                ('Manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.manager_login_information')),
            ],
        ),
    ]
