# Generated by Django 3.1.4 on 2020-12-23 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0031_auto_20201223_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager_login_information',
            name='IT_Service_info',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment_comments_all',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 23, 19, 22, 32, 656009)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 23, 19, 22, 32, 654010)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 23, 19, 22, 32, 654010)),
        ),
        migrations.AlterField(
            model_name='timeoff_staffs_teachers',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 23, 19, 22, 32, 656009)),
        ),
    ]
