# Generated by Django 3.1.4 on 2020-12-23 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0032_auto_20201223_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager_login_information',
            name='IT_Service_info',
        ),
        migrations.AlterField(
            model_name='assignment_comments_all',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 23, 19, 24, 1, 161154)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 23, 19, 24, 1, 159156)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 23, 19, 24, 1, 159156)),
        ),
        migrations.AlterField(
            model_name='timeoff_staffs_teachers',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 23, 19, 24, 1, 162154)),
        ),
    ]
