# Generated by Django 3.1.4 on 2020-12-24 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0035_auto_20201223_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_email_It_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('It_ID', models.CharField(max_length=30)),
                ('It_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment_comments_all',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 24, 20, 20, 16, 877795)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 24, 20, 20, 16, 875797)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 24, 20, 20, 16, 875797)),
        ),
        migrations.AlterField(
            model_name='timeoff_staffs_teachers',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 24, 20, 20, 16, 878795)),
        ),
    ]
