# Generated by Django 3.1.4 on 2021-01-11 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0045_auto_20210111_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_comments_all',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 11, 20, 32, 38, 922084)),
        ),
        migrations.AlterField(
            model_name='list_of_issue',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 11, 20, 32, 38, 923083)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 11, 20, 32, 38, 920085)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 11, 20, 32, 38, 920085)),
        ),
        migrations.AlterField(
            model_name='timeoff_staffs_teachers',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 11, 20, 32, 38, 923083)),
        ),
        migrations.CreateModel(
            name='dean_supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dean_user', models.CharField(max_length=1000)),
                ('Supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.dean_login_information')),
            ],
        ),
    ]
