# Generated by Django 3.1.4 on 2021-01-11 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0049_auto_20210111_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_comments_all',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 12, 0, 12, 54, 373249)),
        ),
        migrations.AlterField(
            model_name='dean_supervisor',
            name='Supervisor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.dean_login_information'),
        ),
        migrations.AlterField(
            model_name='list_of_issue',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 12, 0, 12, 54, 374248)),
        ),
        migrations.AlterField(
            model_name='manager_supervisor',
            name='Supervisor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.dean_login_information'),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 12, 0, 12, 54, 371251)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 12, 0, 12, 54, 371251)),
        ),
        migrations.AlterField(
            model_name='timeoff_staffs_teachers',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 12, 0, 12, 54, 374248)),
        ),
    ]
