# Generated by Django 3.1.4 on 2021-01-13 05:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0056_auto_20210113_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_comments_all',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 13, 11, 35, 12, 458346)),
        ),
        migrations.AlterField(
            model_name='list_of_issue',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 13, 11, 35, 12, 459345)),
        ),
        migrations.AlterField(
            model_name='manager_super_details',
            name='Supervisor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.manager_supervisor'),
        ),
        migrations.AlterField(
            model_name='manager_super_details',
            name='manager_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.manager_login_information'),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 13, 11, 35, 12, 456347)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 13, 11, 35, 12, 456347)),
        ),
        migrations.AlterField(
            model_name='timeoff_staffs_teachers',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 13, 11, 35, 12, 459345)),
        ),
    ]
