from django.contrib import admin
from .models import store_email_teach_new, store_email_stu_new,  Teacher_login_informa, Student_courses_with_Teacher_name, Grade_Student, Student_Submit_Assignment_pro, Teacher_Assignment_upload_File, School, Students, user_staff, Faculties, Department, contractor, store_email_staff_new, Project, status_vacation, Assignment_Comments_all, Student_Login_informations, Student_Course, Admission, Manager_login_information, add_teacher_by_manager, add_students_by_manager, store_email_managers, add_courses, Assign_students_to_courses, Assign_teacher_to_courses, add_staffs_by_manager, store_email_staffs_by_manager, add_Project_by_manager, Timeoff_staffs_teachers, IT_Service_login_Information, Dean_login_information, store_email_It_service, store_email_dean, list_of_issue, User_Information, dean_supervisor, manager_supervisor, manager_super_details
# Register your models here.



admin.site.register(User_Information)
admin.site.register(store_email_teach_new)
admin.site.register(store_email_stu_new)
admin.site.register(Teacher_login_informa)
admin.site.register(Student_courses_with_Teacher_name)
admin.site.register(Grade_Student)
admin.site.register(Student_Submit_Assignment_pro)
admin.site.register(Teacher_Assignment_upload_File)
admin.site.register(School)
admin.site.register(Students)
admin.site.register(user_staff)
admin.site.register(Faculties)
admin.site.register(Department)
admin.site.register(contractor)
admin.site.register(store_email_staff_new)
admin.site.register(Project)
admin.site.register(status_vacation)
admin.site.register(Assignment_Comments_all)
admin.site.register(Student_Login_informations)
admin.site.register(Student_Course)
admin.site.register(Admission)
admin.site.register(Manager_login_information)
admin.site.register(add_teacher_by_manager)
admin.site.register(add_students_by_manager)
admin.site.register(store_email_managers)
admin.site.register(add_courses)
admin.site.register(Assign_students_to_courses)
admin.site.register(Assign_teacher_to_courses)
admin.site.register(add_staffs_by_manager)
admin.site.register(store_email_staffs_by_manager)
admin.site.register(add_Project_by_manager)
admin.site.register(Timeoff_staffs_teachers)
admin.site.register(IT_Service_login_Information)
admin.site.register(Dean_login_information)
admin.site.register(store_email_It_service)
admin.site.register(store_email_dean)
admin.site.register(list_of_issue)
admin.site.register(dean_supervisor)
admin.site.register(manager_supervisor)
admin.site.register(manager_super_details)
