
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_func, name='login'),
    path('logout', views.logout_func, name='logout'),
    path('profile', views.profile, name='profile'),
    path('settings', views.settings, name='settings'),
    path('check_user', views.check_user, name='check_user'),
    path('check_user_password', views.check_user_password, name='check_user_password'),
    path('check_user_student', views.check_user_student, name='check_user_student'),
    path('check_user_password_student', views.check_user_password_student, name='check_user_password_student'),
    path('check_user_staff', views.check_user_staff, name='check_user_staff'),
    path('check_user_staff_password', views.check_user_staff_password, name='check_user_staff_password'),
    path('it_service_page', views.it_service_page, name='it_service_page'),
    path('add_dean_by_it_service', views.add_dean_by_it_service, name='add_dean_by_it_service'),
    path('add_manager_by_it_service', views.add_manager_by_it_service, name='add_manager_by_it_service'),
    path('see_list_student_it', views.see_list_student_it, name='see_list_student_it'),
    path('details_dean_by_it', views.details_dean_by_it, name='details_dean_by_it'),
    path('details_manager_by_it', views.details_manager_by_it, name='details_manager_by_it'),
    path('details_student_by_it', views.details_student_by_it, name='details_student_by_it'),
    path('details_teacher_by_it', views.details_teacher_by_it, name='details_teacher_by_it'),
    path('details_staff_by_it', views.details_staff_by_it, name='details_staff_by_it'),
    path('dean_page', views.dean_page, name='dean_page'),
    path('submit_issue', views.submit_issue, name='submit_issue'),
    path('details_issue', views.details_issue, name='details_issue'),
    path('details_issue_user', views.details_issue_user, name='details_issue_user'),
    path('details_all_in_manager', views.details_all_in_manager, name='details_all_in_manager'),
    path('search_by_dean', views.search_by_dean, name='search_by_dean'),
    path('details_info_students', views.details_info_students, name='details_info_students'),
    path('manager_page', views.manager_page, name='manager_page'),
    path('add_teach_by_manager', views.add_teach_by_manager, name='add_teach_by_manager'),
    path('add_staff_by_manager', views.add_staff_by_manager, name='add_staff_by_manager'),
    path('add_project_by_manager', views.add_project_by_manager, name='add_project_by_manager'),
    path('details_vacations_by_manager', views.details_vacations_by_manager, name='details_vacations_by_manager'),
    path('staff_id_details', views.staff_id_details, name='staff_id_details'),
    path('details_teach_by_manager', views.details_teach_by_manager, name='details_teach_by_manager'),
    path('add_stu_by_manager', views.add_stu_by_manager, name='add_stu_by_manager'),
    path('student_id_details', views.student_id_details, name='student_id_details'),
    path('check_user_dean', views.check_user_dean, name='check_user_dean'),
    path('check_user_it', views.check_user_it, name='check_user_it'),
    path('check_dean_password', views.check_dean_password, name='check_dean_password'),
    path('check_it_password', views.check_it_password, name='check_it_password'),
    path('check_user_manager', views.check_user_manager, name='check_user_manager'),
    path('check_manager_password', views.check_manager_password, name='check_manager_password'),
    path('stu_course', views.stu_course, name='stu_course'),
    path('submit_assignment', views.submit_assignment, name='submit_assignment'),
    path('submit_assignment_student', views.submit_assignment_student, name='submit_assignment_student'),
    path('student_course_list', views.student_course_list, name='student_course_list'),
    path('sir_course', views.sir_course, name='sir_course'),
    path('assignment_page', views.assignment_page, name='assignment_page'),
    path('details_submitted_students', views.details_submitted_students, name='details_submitted_students'),
    path('details_assignment_comments', views.details_assignment_comments, name='details_assignment_comments'),
    path('project_page', views.project_page, name='project_page'),
    path('grading_page', views.grading_page, name='grading_page'),
    path('grading_submit', views.grading_submit, name='grading_submit'),
    path('add_assignment', views.add_assignment, name='add_assignment'),
    path('add_assignment_up_page', views.add_assignment_up_page, name='add_assignment_up_page'),
    path('stu_id_details', views.stu_id_details, name='stu_id_details'),
    path('postComments', views.postComments, name='postComments'),
    path('staff_page', views.staff_page, name='staff_page'),
    path('vacation_day', views.vacation_day, name='vacation_day'),
    path('add_course', views.add_course, name='add_course'),

    path('change_profile_by_it_service/6373672<str:pk>2346533', views.change_dean_profile_by_it, name='change_profile_by_it_service'),
    path('changing_supervisor_dean/6373672<str:pk>2346533', views.changing_supervisor_dean, name='changing_supervisor_dean'),
    path('changing_supervisor_manager/6373672<str:pk>2346533', views.changing_supervisor_manager, name='changing_supervisor_manager'),
    path('change_manager_profile_by_it/<str:pk>', views.change_manager_profile_by_it, name='change_manager_profile_by_it'),
    path('change_stu_profile_by_it_service/<str:pk>', views.change_stu_profile_by_it_service, name='change_stu_profile_by_it_service'),
    path('change_teach_profile_by_it_service/<str:pk>', views.change_teach_profile_by_it_service, name='change_teach_profile_by_it_service'),
    path('change_staff_profile_by_it_service/<str:pk>', views.change_staff_profile_by_it_service, name='change_staff_profile_by_it_service'),
    path('update_change_password/93875995<str:pk>87438737334/345', views.update_change_password, name='update_change_password'),
    path('update_change_password/55649954<str:pk>87436565543/345', views.update_change_password_stu, name='update_change_password_stu'),
    path('update_change_password/34553395<str:pk>87434556645/345', views.update_change_password_staff, name='update_change_password_staff'),
    path('update_change_password/34524595<str:pk>87422226645/345', views.update_change_password_manager, name='update_change_password_manager'),
    path('update_change_password/12322295<str:pk>87422226645/345', views.update_change_password_it, name='update_change_password_it'),
    path('update_change_password/12344295<str:pk>87422226645/345', views.update_change_password_dean, name='update_change_password_dean'),



]